# Data Preprocessing

1. Renaming the columns
2. Dropping email and timestamp
3. Changing the value of data into numerical for statistical work

In [1]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv('response.csv')
df.head()

,Timestamp,Email Address,สถานะสมาชิก,อายุของท่าน,ความถี่ในการเดินห้างเดอะมอลล์/Gourmet Market:,"ปกติเวลาเดินเลือกซื้อสินค้า คุณเคยสังเกตหรือมองหา ""ฉลากคาร์บอนฟุตพริ้นท์ (CFP)"" หรือฉลากสิ่งแวดล้อมบนบรรจุภัณฑ์บ้างหรือไม่?",หากสินค้าที่มีฉลากคาร์บอนต่ำ ให้คะแนนสะสมพิเศษ (Eco-Points) เข้าบัญชี M-Card อัตโนมัติ จะจูงใจให้คุณตัดสินใจเปลี่ยนมาเลือกซื้อสินค้านั้นมากขึ้นหรือไม่?,ระบบสะสม Eco-Points อัตโนมัติ ณ จุดชำระเงิน (POS) โดยสแกนบาร์โค้ดปกติ ไม่ต้องโหลดแอปเพิ่ม หรือติดอุปกรณ์ใหม่ ตอบโจทย์ความสะดวกของคุณมากน้อยเพียงใด?,สิทธิประโยชน์จากการแลก Eco-Points รูปแบบใดที่คุณสนใจและอยากได้มากที่สุด?,"หากใบเสร็จดิจิทัล (Digital Receipt) มีการแสดง ""ปริมาณก๊าซคาร์บอนที่ลดได้ (CO2 Saved)"" และคะแนนที่ได้รับจากการช้อปปิ้งครั้งนั้น คุณรู้สึกอย่างไร?"
0,8/25/2026 19:54:25,NaN,เป็นสมาชิก M-Card,20-35,เดือนละ 1-2 ครั้ง,ประจำ,มากที่สุด (พร้อมเปลี่ยนยี่ห้อทันที),สะดวกมาก (ชอบที่ไม่ต้องทำขั้นตอนเพิ่ม),ส่วนลดคูปองช้อปปิ้ง/คูปองเงินสดในห้างเดอะมอลล์,ช่วยให้ตระหนักเรื่องสิ่งแวดล้อมและอยากซื้อสินค...
1,8/25/2026 19:55:29,NaN,เป็นสมาชิก M-Card,< 20,สัปดาห์ละครั้ง,ไม่เคยสังเกตเลย,ปานกลาง (พิจารณาประกอบกับราคาและคุณภาพ),สะดวกมาก (ชอบที่ไม่ต้องทำขั้นตอนเพิ่ม),แลกรับสินค้ารักษ์โลกพิเศษ,ช่วยให้ตระหนักเรื่องสิ่งแวดล้อมและอยากซื้อสินค...
2,8/25/2026 20:00:37,thanawatkawngam@gmail.com,ยังไม่ได้เป็น,20-35,เดือนละ 1-2 ครั้ง,บางครั้ง (ถ้ามองเห็นชัดเจน),มากที่สุด (พร้อมเปลี่ยนยี่ห้อทันที),สะดวกมาก (ชอบที่ไม่ต้องทำขั้นตอนเพิ่ม),ส่วนลดคูปองช้อปปิ้ง/คูปองเงินสดในห้างเดอะมอลล์,ช่วยให้ตระหนักเรื่องสิ่งแวดล้อมและอยากซื้อสินค...
3,8/25/2026 20:24:36,aris.poo@student.mahidol.edu,เป็นสมาชิก M-Card,20-35,เดือนละ 1-2 ครั้ง,ไม่เคยสังเกตเลย,ปานกลาง (พิจารณาประกอบกับราคาและคุณภาพ),สะดวกมาก (ชอบที่ไม่ต้องทำขั้นตอนเพิ่ม),ส่วนลดคูปองช้อปปิ้ง/คูปองเงินสดในห้างเดอะมอลล์,ช่วยให้ตระหนักเรื่องสิ่งแวดล้อมและอยากซื้อสินค...
4,8/25/2026 21:13:23,nnpmild23@gmail.com,ยังไม่ได้เป็น,< 20,เดือนละ 1-2 ครั้ง,บางครั้ง (ถ้ามองเห็นชัดเจน),ปานกลาง (พิจารณาประกอบกับราคาและคุณภาพ),สะดวกมาก (ชอบที่ไม่ต้องทำขั้นตอนเพิ่ม),ส่วนลดคูปองช้อปปิ้ง/คูปองเงินสดในห้างเดอะมอลล์,ช่วยให้ตระหนักเรื่องสิ่งแวดล้อมและอยากซื้อสินค...

In [24]:
# 1. Renaming the columns
df.columns = [
    'timestamp', 
    'email',
    'membership_status', 
    'age_group', 
    'visit_frequency',
    'notice_cfp_label',
    'motivated_by_eco_points',
    'pos_convenience',
    'preferred_eco_benefits',
    'feeling_on_digital_receipt'
]
df.head()

,timestamp,email,membership_status,age_group,visit_frequency,notice_cfp_label,motivated_by_eco_points,pos_convenience,preferred_eco_benefits,feeling_on_digital_receipt
0,8/25/2026 19:54:25,NaN,เป็นสมาชิก M-Card,20-35,เดือนละ 1-2 ครั้ง,ประจำ,มากที่สุด (พร้อมเปลี่ยนยี่ห้อทันที),สะดวกมาก (ชอบที่ไม่ต้องทำขั้นตอนเพิ่ม),ส่วนลดคูปองช้อปปิ้ง/คูปองเงินสดในห้างเดอะมอลล์,ช่วยให้ตระหนักเรื่องสิ่งแวดล้อมและอยากซื้อสินค...
1,8/25/2026 19:55:29,NaN,เป็นสมาชิก M-Card,< 20,สัปดาห์ละครั้ง,ไม่เคยสังเกตเลย,ปานกลาง (พิจารณาประกอบกับราคาและคุณภาพ),สะดวกมาก (ชอบที่ไม่ต้องทำขั้นตอนเพิ่ม),แลกรับสินค้ารักษ์โลกพิเศษ,ช่วยให้ตระหนักเรื่องสิ่งแวดล้อมและอยากซื้อสินค...
2,8/25/2026 20:00:37,thanawatkawngam@gmail.com,ยังไม่ได้เป็น,20-35,เดือนละ 1-2 ครั้ง,บางครั้ง (ถ้ามองเห็นชัดเจน),มากที่สุด (พร้อมเปลี่ยนยี่ห้อทันที),สะดวกมาก (ชอบที่ไม่ต้องทำขั้นตอนเพิ่ม),ส่วนลดคูปองช้อปปิ้ง/คูปองเงินสดในห้างเดอะมอลล์,ช่วยให้ตระหนักเรื่องสิ่งแวดล้อมและอยากซื้อสินค...
3,8/25/2026 20:24:36,aris.poo@student.mahidol.edu,เป็นสมาชิก M-Card,20-35,เดือนละ 1-2 ครั้ง,ไม่เคยสังเกตเลย,ปานกลาง (พิจารณาประกอบกับราคาและคุณภาพ),สะดวกมาก (ชอบที่ไม่ต้องทำขั้นตอนเพิ่ม),ส่วนลดคูปองช้อปปิ้ง/คูปองเงินสดในห้างเดอะมอลล์,ช่วยให้ตระหนักเรื่องสิ่งแวดล้อมและอยากซื้อสินค...
4,8/25/2026 21:13:23,nnpmild23@gmail.com,ยังไม่ได้เป็น,< 20,เดือนละ 1-2 ครั้ง,บางครั้ง (ถ้ามองเห็นชัดเจน),ปานกลาง (พิจารณาประกอบกับราคาและคุณภาพ),สะดวกมาก (ชอบที่ไม่ต้องทำขั้นตอนเพิ่ม),ส่วนลดคูปองช้อปปิ้ง/คูปองเงินสดในห้างเดอะมอลล์,ช่วยให้ตระหนักเรื่องสิ่งแวดล้อมและอยากซื้อสินค...

In [25]:
# 2. Dropping email and timestamp
df = df.drop(columns=['timestamp', 'email'])
df.head()

,membership_status,age_group,visit_frequency,notice_cfp_label,motivated_by_eco_points,pos_convenience,preferred_eco_benefits,feeling_on_digital_receipt
0,เป็นสมาชิก M-Card,20-35,เดือนละ 1-2 ครั้ง,ประจำ,มากที่สุด (พร้อมเปลี่ยนยี่ห้อทันที),สะดวกมาก (ชอบที่ไม่ต้องทำขั้นตอนเพิ่ม),ส่วนลดคูปองช้อปปิ้ง/คูปองเงินสดในห้างเดอะมอลล์,ช่วยให้ตระหนักเรื่องสิ่งแวดล้อมและอยากซื้อสินค...
1,เป็นสมาชิก M-Card,< 20,สัปดาห์ละครั้ง,ไม่เคยสังเกตเลย,ปานกลาง (พิจารณาประกอบกับราคาและคุณภาพ),สะดวกมาก (ชอบที่ไม่ต้องทำขั้นตอนเพิ่ม),แลกรับสินค้ารักษ์โลกพิเศษ,ช่วยให้ตระหนักเรื่องสิ่งแวดล้อมและอยากซื้อสินค...
2,ยังไม่ได้เป็น,20-35,เดือนละ 1-2 ครั้ง,บางครั้ง (ถ้ามองเห็นชัดเจน),มากที่สุด (พร้อมเปลี่ยนยี่ห้อทันที),สะดวกมาก (ชอบที่ไม่ต้องทำขั้นตอนเพิ่ม),ส่วนลดคูปองช้อปปิ้ง/คูปองเงินสดในห้างเดอะมอลล์,ช่วยให้ตระหนักเรื่องสิ่งแวดล้อมและอยากซื้อสินค...
3,เป็นสมาชิก M-Card,20-35,เดือนละ 1-2 ครั้ง,ไม่เคยสังเกตเลย,ปานกลาง (พิจารณาประกอบกับราคาและคุณภาพ),สะดวกมาก (ชอบที่ไม่ต้องทำขั้นตอนเพิ่ม),ส่วนลดคูปองช้อปปิ้ง/คูปองเงินสดในห้างเดอะมอลล์,ช่วยให้ตระหนักเรื่องสิ่งแวดล้อมและอยากซื้อสินค...
4,ยังไม่ได้เป็น,< 20,เดือนละ 1-2 ครั้ง,บางครั้ง (ถ้ามองเห็นชัดเจน),ปานกลาง (พิจารณาประกอบกับราคาและคุณภาพ),สะดวกมาก (ชอบที่ไม่ต้องทำขั้นตอนเพิ่ม),ส่วนลดคูปองช้อปปิ้ง/คูปองเงินสดในห้างเดอะมอลล์,ช่วยให้ตระหนักเรื่องสิ่งแวดล้อมและอยากซื้อสินค...

In [26]:
# 3. Changing the value of data into numerical for statistical work

mem_map = {
    'เป็นสมาชิก M-Card': 1,
    'ยังไม่ได้เป็น': 0
}
df['membership_status'] = df['membership_status'].map(mem_map)

freq_map = {
    'สัปดาห์ละหลายครั้ง': 3,
    'สัปดาห์ละครั้ง': 3,
    'เดือนละ 1-2 ครั้ง': 2,
    'นานๆครั้ง': 1
}
df['visit_frequency'] = df['visit_frequency'].map(freq_map)

notice_map = {
    'ประจำ': 3,
    'บางครั้ง (ถ้ามองเห็นชัดเจน)': 2,
    'ไม่เคยสังเกตเลย': 1
}
df['notice_cfp_label'] = df['notice_cfp_label'].map(notice_map)

motiv_map = {
    'มากที่สุด (พร้อมเปลี่ยนยี่ห้อทันที)': 3,
    'ปานกลาง (พิจารณาประกอบกับราคาและคุณภาพ)': 2,
    'น้อย / ไม่มีผลต่อการตัดสินใจ': 1
}
df['motivated_by_eco_points'] = df['motivated_by_eco_points'].map(motiv_map)

conv_map = {
    'สะดวกมาก (ชอบที่ไม่ต้องทำขั้นตอนเพิ่ม)': 3,
    'ปานกลาง': 2,
    'ไม่สะดวก': 1
}
df['pos_convenience'] = df['pos_convenience'].map(conv_map)

feel_map = {
    'ช่วยให้ตระหนักเรื่องสิ่งแวดล้อมและอยากซื้อสินค้ารักษ์โลกเพิ่มขึ้น': 3,
    'เฉยๆ / ไม่ได้สนใจข้อมูลนี้': 1
}
df['feeling_on_digital_receipt'] = df['feeling_on_digital_receipt'].map(feel_map)

# One-hot encode preferred_eco_benefits and rename columns
benefits_dummies = df['preferred_eco_benefits'].str.get_dummies(sep=', ')
benefits_dummies = benefits_dummies.rename(columns={
    'นำคะแนนไปร่วมบริจาคโครงการสิ่งแวดล้อม': 'donate_to_environment',
    'ส่วนลดคูปองช้อปปิ้ง/คูปองเงินสดในห้างเดอะมอลล์': 'shopping_discount_coupon',
    'แลกรับสินค้ารักษ์โลกพิเศษ': 'redeem_eco_product'
})
df = pd.concat([df.drop(columns=['preferred_eco_benefits']), benefits_dummies], axis=1)

df.head()

,membership_status,age_group,visit_frequency,notice_cfp_label,motivated_by_eco_points,pos_convenience,feeling_on_digital_receipt,donate_to_environment,shopping_discount_coupon,redeem_eco_product
0,1,20-35,2,3,3,3,3,0,1,0
1,1,< 20,3,1,2,3,3,0,0,1
2,0,20-35,2,2,3,3,3,0,1,0
3,1,20-35,2,1,2,3,3,0,1,0
4,0,< 20,2,2,2,3,3,0,1,0

In [27]:
# Save the cleaned data
df.to_csv('cleaned_response.csv', index=False)
print('Data preprocessing complete. Saved to cleaned_response.csv')

Data preprocessing complete. Saved to cleaned_response.csv